---
Name: ideannotator
---
SilverStripe\Dev\DevBuildController:
  extensions:
    - SilverLeague\IDEAnnotator\Extensions\Annotatable
SilverLeague\IDEAnnotator\DataObjectAnnotator:
    enabled_modules:
      - mysite
      - app
    dbfield_tagnames:
      SilverStripe\ORM\FieldType\DBInt: int
      SilverStripe\ORM\FieldType\DBBoolean: bool
      SilverStripe\ORM\FieldType\DBFloat: float
      SilverStripe\ORM\FieldType\DBDecimal: float
